
version: 2

models:
    - name: customers
      description: "Customers dbt model"
      columns:
          - name: first_order_date
            description: "should not be null"
            tests:
                - not_null